project          = "keto-gcp-dev-esa-app"
organization_id  = "855338854565"
billing_account  = "0136D5-6610C1-CADBF2"
credentials_path = "/workspace/secrets/credentials.json"
region           = "us-east4"
instance_name    = "esa-dev-sample"
